name: "Setup Molecule"
author: "Patrick Becker"
description: "Set up the Ansible testing framework Molecule with Docker."
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        check-latest: true
        cache: "pip"

    - run: pip install -r requirements.txt
      shell: bash

    - run: ansible --version
      shell: bash

    - run: molecule --version
      shell: bash
branding:
  icon: "code"
  color: "white"
