---
name: Test

"on":
  push:
    branches:
      - main
  schedule:
    # At 06:00 UTC, on day 1 of the month.
    - cron: "0 6 1 * *"

jobs:
  test:
    name: Test Molecule packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3

      - name: Setup Molecule
        uses: ./
